<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[TestA...]]>
    </line>
    <line>
      <![CDATA[testA is PASSED]]>
    </line>
    <line>
      <![CDATA[TestB...]]>
    </line>
    <line>
      <![CDATA[testB is FAILED]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="64" started-at="2018-03-04T07:18:18Z" finished-at="2018-03-04T07:18:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="64" started-at="2018-03-04T07:18:18Z" finished-at="2018-03-04T07:18:18Z">
      <class name="script.TEST_CLASS">
        <test-method status="PASS" signature="testA()[pri:0, instance:script.TEST_CLASS@5c3bd550]" name="testA" duration-ms="13" started-at="2018-03-04T12:48:18Z" finished-at="2018-03-04T12:48:18Z">
          <reporter-output>
            <line>
              <![CDATA[TestA...]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="end(org.testng.ITestResult)[pri:0, instance:script.TEST_CLASS@5c3bd550]" name="end" is-config="true" duration-ms="1" started-at="2018-03-04T12:48:18Z" finished-at="2018-03-04T12:48:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=SUCCESS method=TEST_CLASS.testA()[pri:0, instance:script.TEST_CLASS@5c3bd550] output=TestA...]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testA is PASSED]]>
            </line>
          </reporter-output>
        </test-method> <!-- end -->
        <test-method status="FAIL" signature="testB()[pri:0, instance:script.TEST_CLASS@5c3bd550]" name="testB" duration-ms="4" started-at="2018-03-04T12:48:18Z" finished-at="2018-03-04T12:48:18Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: nullat org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.fail(Assert.java:103)at script.TEST_CLASS.testB(TEST_CLASS.java:17)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[TestB...]]>
            </line>
          </reporter-output>
        </test-method> <!-- testB -->
        <test-method status="PASS" signature="end(org.testng.ITestResult)[pri:0, instance:script.TEST_CLASS@5c3bd550]" name="end" is-config="true" duration-ms="10" started-at="2018-03-04T12:48:18Z" finished-at="2018-03-04T12:48:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testB status=FAILURE method=TEST_CLASS.testB()[pri:0, instance:script.TEST_CLASS@5c3bd550] output=TestB...]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[testB is FAILED]]>
            </line>
          </reporter-output>
        </test-method> <!-- end -->
      </class> <!-- script.TEST_CLASS -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
